
package org.certific.tarjetadigital.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "InscripcionService", targetNamespace = "http://Service.TarjetaDigital.certific.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface InscripcionService {


    /**
     * 
     * @return
     *     returns java.util.List<org.certific.tarjetadigital.service.Inscripcion>
     */
    @WebMethod(operationName = "ObtenerInscripciones")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ObtenerInscripciones", targetNamespace = "http://Service.TarjetaDigital.certific.org/", className = "org.certific.tarjetadigital.service.ObtenerInscripciones")
    @ResponseWrapper(localName = "ObtenerInscripcionesResponse", targetNamespace = "http://Service.TarjetaDigital.certific.org/", className = "org.certific.tarjetadigital.service.ObtenerInscripcionesResponse")
    public List<Inscripcion> obtenerInscripciones();

    /**
     * 
     * @param arg0
     * @return
     *     returns org.certific.tarjetadigital.service.Response
     */
    @WebMethod(operationName = "CrearInscripcion")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "CrearInscripcion", targetNamespace = "http://Service.TarjetaDigital.certific.org/", className = "org.certific.tarjetadigital.service.CrearInscripcion")
    @ResponseWrapper(localName = "CrearInscripcionResponse", targetNamespace = "http://Service.TarjetaDigital.certific.org/", className = "org.certific.tarjetadigital.service.CrearInscripcionResponse")
    public Response crearInscripcion(
        @WebParam(name = "arg0", targetNamespace = "")
        Inscripcion arg0);

}
